build:
	gcc -Wall -Wextra -pedantic -std=c11 00-introduction.c -o 00-introduction.out
	gcc -Wall -Wextra -pedantic -std=c11 02-exec.c -o 02-exec.out
	gcc -Wall -Wextra -pedantic -std=c11 03-exec.c -o 03-exec.out

clean:
	rm *.out

