build:
	gcc -Wall -Wextra -pedantic -std=c11 00-introduction.c -o 00-introduction.out
	gcc -Wall -Wextra -pedantic -std=c11 01-cat.c -o 01-cat.out
	gcc -Wall -Wextra -pedantic -std=c11 02-one-third-cat.c -o 02-one-third-cat.out

clean:
	rm *.out

